# docker-compose.yml

version: '3.8'

services:
  app:
    build:
      context: .
    container_name: bulk_email_app
    image: bulk-email-processor
    ports:
      - '3000:3000'
    restart: unless-stopped
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - db
      - rabbitmq
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bulk-email-processor
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
